alias pcdev5="ssh avi.vajpeyi@ldas-pcdev5.ligo.caltech.edu"
alias tess_loads="source /Users/avaj0001/Documents/projects/tess/tess_venv/bin/activate"
alias bfg='java -jar /usr/local/bin/bfg-latest.jar'
alias cdp='cd ~/Documents/projects/'
alias vacti='source venv/bin/activate && which python'
alias clock='tty-clock -s -c'
alias cleantex='rm -r -f *.aux *.log *.lof *.gz *.toc *.bak~ *.dvi *.out *.bbl *.blg *.fls *.end'
alias speedtest='~/.speedtest-cli'
alias grep='grep --color=auto'
alias ls='ls -GFh'
alias lh='ls -Alh  -altr'
alias ozstar='ssh -X avajpeyi@ozstar.swin.edu.au'
alias pip='pip3'
alias python='python3'
alias ligo_init='ligo-proxy-init avi.vajpeyi'
alias sshoz='ssh -X avajpeyi@ozstar.swin.edu.au'
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
